### ISSUE TITLE
User can create groups without being in it

### ISSUE THREAD

**Issue by thisIsTheFoxe** [ingokuba/swing-chat#37]
The group can still be created and shows up on other (selected) windows.. can cause group spamming .-.

**Comment by ingokuba** [comment]
Yeah well :man_shrugging: why not? I hate that I have to create WhatsApp groups and leave them when I want to force people to be in a WhatsApp group :wink:

**Comment by thisIsTheFoxe** [comment]
Hmm.. seems legit..  ![https://giphy.com/gifs/reactiongifs-13ZHjidRzoi7n2]
