### ISSUE TITLE
Change group buttons

### ISSUE THREAD

**Issue by thisIsTheFoxe** [ingokuba/swing-chat#38]
Button doesn't feel intuitive.. I expect something to happen, but that not always the case..

maybe use radio-buttons or single-selects? or let the selected groupBtn stay selected until the sender-list changes..

wdyt?

**Comment by ingokuba** [comment]
Good idea, I implemented at simple first :)

**Comment by thisIsTheFoxe** [comment]
![ok](https://giphy.com/gifs/Bounce-TV-cool-ok-thumbs-up-4PSEQpvV5wUpnmpP1l)

**Comment by ingokuba** [comment]
how does one use GIFs? :scream: Markdown?
